nome = input('Qual é o seu nome?')
print('É um prazer em te conhcer', nome,'!')
print(' ')
print('Seja bem vindo {}!'.format(nome))
print('')
print(f'Foi uma honra programar com o seu nome, {nome}!')
