nome = str(input('Digite seu Nome Completo: ')).strip()
print('------------------------------------')
print(' ANÁLISE DO SEU NOME \n INICIANDO...')
print('------------------------------------')
print(f'Nome Maiúsculo: {nome.upper()}')
print(f'Nome Minúsculo: {nome.lower()}')
print(f'Letras: {len(nome) - nome.count(" ")}')
#print(f'Letras 1° nome: {nome.find(" ")}')
div = nome.split()
print(f'Seu primeiro nome {div[0]} tem {len(div[0])} letras')
